### ISSUE TITLE
Add version

### ISSUE THREAD

**Issue by Ambrevar** [hu-dwim/hu.dwim.defclass-star#10]
The systems don't have versions.

I recently got a bug report from someone who is using Quicklisp's version of defclass-star, and quicklisp is following the `stable` branch.

To allow library developers to specify a dependency on a more recent version of defclass-star (such as the use of automatically generated predicates), I suggest we add a version number to the system.

**Comment by attila-lendvai** [comment]
to be honest, i don't feel like dealing with versioning... but i do recognize that there's a source of headache here.

for now i have moved the `stable` tag so ql will pick up all your recent fixes.

i'll probably forget to move the ql tag every once in a while... just like how i would forget updating the version string.

**Comment by Ambrevar** [comment]
Thanks!

Indeed, moving the tag and updating the version string amounts to the
same maintenance burden.  So why not use a version string then?

This is what I do on a new version release:

- Update the .asd version.
- Commit.
- Tag the commit with the version number.

It's simple enough and there is nothing to forget here, you just release
once in a while.

Thoughts?

**Comment by attila-lendvai** [comment]
i have pushed a proposed solution, and also marked it as 1.0.0. take a look please, including the commits!

i also fixed the tests, they were broken by the predicate change.

predicate generation also upset our entire codebase, which i decided not to fix for now... i have mixed feelings about generating a predicate by default. it's clutter for those users who don't need it, using up memory, etc. i can imagine a library that has a lot of classes, but doesn't need all those predicates.

**Comment by Ambrevar** [comment]
I'm OK with disabling the predicate generation by default :)

**Comment by Ambrevar** [comment]
I've looked at the commits, they look good to me, although I haven't
tested anything in particular.

About version 1.0.0: can you push a corresponding Git tag?
This is to make it easier for packagers (e.g. the Guix or Quicklisp packages).

**Comment by attila-lendvai** [comment]
i'll sleep on the default for predicate generation, then create a tag.

the entire point of this project is to decrease verbosity, and the wrong default means a new line for most `defclass*` forms. but side effecting the global variable is a very bad idea, because it would affect code compiled afterwards. they sholdn't even be bound by default, i'll double check that.

**Comment by attila-lendvai** [comment]
i've pushed a `v1.0.0` tag.
