### ISSUE TITLE
Question: How do you get to automatically indent defclass* like defclass in Emacs?

### ISSUE THREAD

**Issue by Ambrevar** [hu-dwim/hu.dwim.defclass-star#11]
See the leading space difference when indenting with Emacs:

```lisp
(hu.dwim.defclass-star:defclass* foo ()
    ((name :type string)))

(defclass* foo ()
    ((name :type string)))

(defclass foo ()
  ((name :type string)))
```

Is there a way to change this indentation behaviour?
One thing Emacs does is recognize symbols that start with `define-` or `with-`.
So having `define-class` would solve this issue.

**Comment by attila-lendvai** [comment]
i've added some emacs integration with this: https://github.com/hu-dwim/hu.dwim.defclass-star/commit/73a5306d874afbeb2727fb77f496063b18d116a3

please take a look, and let me know how it works on your side, or just open a PR if you had to tailor this... :)

**Comment by Ambrevar** [comment]
Thanks, works well except that I had to change `first` to `cl-first` and
`second` to `cl-second`.

**Comment by attila-lendvai** [comment]
pushed an update. let me know if there are any issues left!
